<?php

echo "<h6>CONSTANTES PRE-DEFINIDAS</h6>";

echo "VERSAO DO PHP INSTALADA NO SERVIDOR WEB: " . PHP_VERSION . "<br>";

echo "SABER O DIRECTORY SEPARATOR ASSOCIADO AO SO: " . DIRECTORY_SEPARATOR;
